# fly.toml app configuration file generated for full-stack-open-pokedex-still-night-7521 on 2025-08-20T14:08:19+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-still-night-7521'
primary_region = 'arn'

[build]

[env]
  PORT = "3000"

[processes]
  app = "node app.js" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
